table customer_churn_clean
	lineageTag: 4b2faa91-1103-4c60-9483-0667462ea911

	column customerid
		dataType: string
		lineageTag: 10065995-283b-4ad4-bd9a-fb610aec5130
		summarizeBy: none
		sourceColumn: customerid

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 2cba1417-aba1-4619-aa7b-30e51faa92e7
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: int64
		formatString: 0
		lineageTag: cf436870-5865-4e65-b811-4ff462377c6d
		dataCategory: PostalCode
		summarizeBy: sum
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 7f0ad93d-f896-490f-89e2-9ab2494dbe4a
		dataCategory: Latitude
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 2043dc13-c1d5-45b5-8a52-617b193c1863
		dataCategory: Longitude
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gender
		dataType: string
		lineageTag: 8c7b4ea2-b209-40fb-acfb-f9de5be22b0a
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column senior_citizen
		dataType: string
		lineageTag: 1cccf689-cd56-4c2c-a1b1-c79cd0bc21bb
		summarizeBy: none
		sourceColumn: senior_citizen

		annotation SummarizationSetBy = Automatic

	column partner
		dataType: string
		lineageTag: 220aed9b-8dbb-4127-9403-ae200583d547
		summarizeBy: none
		sourceColumn: partner

		annotation SummarizationSetBy = Automatic

	column dependents
		dataType: string
		lineageTag: 92183580-6f7b-4a1a-98a5-98c11d97a75e
		summarizeBy: none
		sourceColumn: dependents

		annotation SummarizationSetBy = Automatic

	column tenure_months
		dataType: int64
		formatString: 0
		lineageTag: 3c833bcf-38e0-4238-a1a9-182b6d09a8d1
		summarizeBy: sum
		sourceColumn: tenure_months

		annotation SummarizationSetBy = Automatic

	column phone_service
		dataType: string
		lineageTag: c2f43e30-afd6-4103-92b6-84ac8f2791f1
		summarizeBy: none
		sourceColumn: phone_service

		annotation SummarizationSetBy = Automatic

	column multiple_lines
		dataType: string
		lineageTag: 5db84bee-66dc-48ff-ba3a-72b5446f34a7
		summarizeBy: none
		sourceColumn: multiple_lines

		annotation SummarizationSetBy = Automatic

	column internet_service
		dataType: string
		lineageTag: a676152f-b8fa-4dcc-998d-1d3a62542cb4
		summarizeBy: none
		sourceColumn: internet_service

		annotation SummarizationSetBy = Automatic

	column online_security
		dataType: string
		lineageTag: 4f13b8fe-bcbf-4af9-982f-cd3538e53f93
		summarizeBy: none
		sourceColumn: online_security

		annotation SummarizationSetBy = Automatic

	column online_backup
		dataType: string
		lineageTag: b914f46a-13fd-4872-932c-ef1fc889bd5e
		summarizeBy: none
		sourceColumn: online_backup

		annotation SummarizationSetBy = Automatic

	column device_protection
		dataType: string
		lineageTag: 755a7d9f-90f0-43de-81b4-0a8649ab7a5a
		summarizeBy: none
		sourceColumn: device_protection

		annotation SummarizationSetBy = Automatic

	column tech_support
		dataType: string
		lineageTag: e66ce020-b31a-4694-8213-cc66c0b6728d
		summarizeBy: none
		sourceColumn: tech_support

		annotation SummarizationSetBy = Automatic

	column streaming_tv
		dataType: string
		lineageTag: a5369f4e-f4c4-4a57-9bff-91256ed92bdc
		summarizeBy: none
		sourceColumn: streaming_tv

		annotation SummarizationSetBy = Automatic

	column streaming_movies
		dataType: string
		lineageTag: 042fd294-53e9-44fb-84a3-45bd6d68e671
		summarizeBy: none
		sourceColumn: streaming_movies

		annotation SummarizationSetBy = Automatic

	column contract
		dataType: string
		lineageTag: 6f1af6ba-54a6-4d90-8409-95cca7ee392a
		summarizeBy: none
		sourceColumn: contract

		annotation SummarizationSetBy = Automatic

	column paperless_billing
		dataType: string
		lineageTag: c1119368-fe8a-4c89-8b79-e0eff27cf2d7
		summarizeBy: none
		sourceColumn: paperless_billing

		annotation SummarizationSetBy = Automatic

	column payment_method
		dataType: string
		lineageTag: 55fd1548-d1de-46ed-a4f0-ebf089e7df8e
		summarizeBy: none
		sourceColumn: payment_method

		annotation SummarizationSetBy = Automatic

	column monthly_charges
		dataType: double
		lineageTag: ae34c512-6ab9-41e8-bead-989c72420b88
		summarizeBy: sum
		sourceColumn: monthly_charges

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_charges
		dataType: double
		lineageTag: 41816119-31f6-40be-ad8c-252e7b9f6c25
		summarizeBy: sum
		sourceColumn: total_charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column churn_label
		dataType: string
		lineageTag: 8205b6fd-5dd8-4bbf-bec1-21fca2fc84ee
		summarizeBy: none
		sourceColumn: churn_label

		annotation SummarizationSetBy = Automatic

	column churn_value
		dataType: int64
		formatString: 0
		lineageTag: 399d5ebe-ddc1-4398-bbdd-dc493f539f29
		summarizeBy: sum
		sourceColumn: churn_value

		annotation SummarizationSetBy = Automatic

	column churn_score
		dataType: int64
		formatString: 0
		lineageTag: c31c90d3-7608-4cbe-a3d6-37abb1e0cc3d
		summarizeBy: sum
		sourceColumn: churn_score

		annotation SummarizationSetBy = Automatic

	column cltv
		dataType: int64
		formatString: 0
		lineageTag: 0c0701b5-9849-4c03-8362-5f0137c2b756
		summarizeBy: sum
		sourceColumn: cltv

		annotation SummarizationSetBy = Automatic

	column tenure_group
		dataType: string
		lineageTag: d2c19b50-db58-4e03-9462-24eefd09d841
		summarizeBy: none
		sourceColumn: tenure_group

		annotation SummarizationSetBy = Automatic

	column avg_monthly_usage
		dataType: double
		lineageTag: 9efff7e4-eebb-40ca-864a-7b63767c613f
		summarizeBy: sum
		sourceColumn: avg_monthly_usage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payment_risk
		dataType: string
		lineageTag: 20352d50-3e97-4d1e-b887-883f4e1ad1f5
		summarizeBy: none
		sourceColumn: payment_risk

		annotation SummarizationSetBy = Automatic

	column customer_value_segment
		dataType: string
		lineageTag: ed3be6b4-7c99-4a95-80ca-019e77053ee6
		summarizeBy: none
		sourceColumn: customer_value_segment

		annotation SummarizationSetBy = Automatic

	column total_services
		dataType: int64
		formatString: 0
		lineageTag: 6d15ab0a-ebd8-434a-ad0c-4be88172fbb6
		summarizeBy: sum
		sourceColumn: total_services

		annotation SummarizationSetBy = Automatic

	partition customer_churn_clean = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("E:\NCPL\Bootcamp\Project 1\Data Files\customer_churn_clean.csv"), [Delimiter = ",", Columns = 33, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"customerid", type text}, {"city", type text}, {"zip_code", Int64.Type}, {"latitude", type number}, {"longitude", type number}, {"gender", type text}, {"senior_citizen", type text}, {"partner", type text}, {"dependents", type text}, {"tenure_months", Int64.Type}, {"phone_service", type text}, {"multiple_lines", type text}, {"internet_service", type text}, {"online_security", type text}, {"online_backup", type text}, {"device_protection", type text}, {"tech_support", type text}, {"streaming_tv", type text}, {"streaming_movies", type text}, {"contract", type text}, {"paperless_billing", type text}, {"payment_method", type text}, {"monthly_charges", type number}, {"total_charges", type number}, {"churn_label", type text}, {"churn_value", Int64.Type}, {"churn_score", Int64.Type}, {"cltv", Int64.Type}, {"tenure_group", type text}, {"avg_monthly_usage", type number}, {"payment_risk", type text}, {"customer_value_segment", type text}, {"total_services", Int64.Type}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

